### ISSUE TITLE
holy unblocker dosent work

### ISSUE THREAD

**Issue by MrMachi9** [TheKing349/HolyUnblockerPublic#1]
i cant access holy unblocker because my chrome book just got fixed so the holy unblocker dosent work

**Comment by TheKing349** [comment]
> i cant access holy unblocker because my chrome book just got fixed so the holy unblocker dosent work

Yeah this was just a test. Go to  https://github.com/QuiteAFancyEmerald/Holy-Unblocker to see how to build it to your own PC or the actual website
